import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import Database from "better-sqlite3";
import { afterEach, describe, expect, it } from "vitest";
import { closeDatabase, initializeDatabase } from "./db.js";
import { createMigratedDatabase } from "./test-database.js";

describe("db", () => {
	let dir: string | undefined;

	afterEach(async () => {
		closeDatabase();
		if (dir) {
			await rm(dir, { recursive: true, force: true });
		}
	});

	it("opens a database generated by Drizzle migrations", async () => {
		dir = await mkdtemp(join(tmpdir(), "mini-claw-db-"));
		const dbPath = join(dir, "miniclaw.db");
		createMigratedDatabase(dbPath);

		initializeDatabase(dbPath);

		const sqlite = new Database(dbPath);
		const tables = sqlite
			.prepare("SELECT name FROM sqlite_master WHERE type = 'table'")
			.all() as { name: string }[];
		sqlite.close();
		expect(tables.map((table) => table.name)).toEqual(
			expect.arrayContaining([
				"__drizzle_migrations",
				"sessions",
				"messages",
				"cron_jobs",
				"cron_capabilities",
			]),
		);
	});

	it("rejects a missing database file without creating one", async () => {
		dir = await mkdtemp(join(tmpdir(), "mini-claw-db-"));
		const dbPath = join(dir, "miniclaw.db");

		expect(() => initializeDatabase(dbPath)).toThrow("Database file not found");
		expect(() => new Database(dbPath, { fileMustExist: true })).toThrow();
	});

	it("rejects unmigrated database files", async () => {
		dir = await mkdtemp(join(tmpdir(), "mini-claw-db-"));
		const dbPath = join(dir, "miniclaw.db");
		await writeFile(dbPath, "");

		expect(() => initializeDatabase(dbPath)).toThrow(
			"Database is missing required table 'sessions'",
		);
	});

	it("rejects old user-scoped session databases", async () => {
		dir = await mkdtemp(join(tmpdir(), "mini-claw-db-"));
		const dbPath = join(dir, "miniclaw.db");
		const sqlite = new Database(dbPath);
		sqlite.exec(`
			CREATE TABLE sessions (
				id TEXT NOT NULL PRIMARY KEY,
				userId TEXT NOT NULL,
				createdAt TEXT NOT NULL,
				model TEXT NOT NULL,
				thinkingLevel TEXT NOT NULL,
				budget_low INTEGER NOT NULL DEFAULT 0
			);
		`);
		sqlite.close();

		expect(() => initializeDatabase(dbPath)).toThrow("unsupported old sessions schema");
	});
});
